parameters:
  mailer_sender: '%env(MAILER_SENDER)%'
  jinya_version: 7.0.0
  jinya_gallery.temp_dir: '%kernel.project_dir%/var/tmp'
  jinya_gallery.profiler.out_dir: '%kernel.project_dir%/var/profiler'
  jinya_gallery.theme.directory: themes

jinya_profiling:
  out_dir: '%jinya_gallery.profiler.out_dir%'
  enabled: true