--- 
defaults: 
  docker: 
    - 
      image: circleci/php
  working_directory: ~/jinya
jobs: 
  build: 
    docker: 
      - 
        image: circleci/php
    steps: 
      - checkout
      - 
        run: 
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt update
            sudo apt install -y nodejs build-essential yarn
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"composer.json\" }}"
            - v1-dependencies-
      - 
        run: "composer install -n --prefer-dist --no-scripts --no-dev"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"composer.json\" }}"
          paths: 
            - ./vendor
      - 
        run: 
          command: |
            cd themes/jinya_gallery_default_theme/Designer/
            yarn yarn build
      - 
        run: 
          command: |
            cd themes/jinya_gallery_default_theme/Frontend/
            yarn node_modules/.bin/gulp
      - 
        run: 
          command: |
            rm -rf themes/jinya_gallery_default_theme/Frontend/node_modules themes/jinya_gallery_default_theme/Designer/node_modules var/cache var/log public/public
            mkdir -p ~/dist
            zip -r ~/jinya ~/dist/$(date +\"%Y-%m-%d_%H-%M-%S\").zip
      - 
        persist_to_workspace: 
          paths: 
            - dist
          root: ~/jinya
    working_directory: ~/jinya
  deployEdge: 
    docker: 
      - 
        image: circleci/php
    steps: 
      - 
        attach_workspace: 
          at: ~/jinya/
      - 
        run: 
          command: "scp -r ~/jinya/dist $DEPLOY_LOGIN@$DEPLOY_SERVER:$DEPLOY_TARGET/cms/edge ssh $DEPLOY_LOGIN@$DEPLOY_SERVER \"php_cli $DEPLOY_TARGET/bin/console jinya:version:update edge\"\n"
          name: "Deploy via SCP"
    working_directory: ~/jinya
  deployNightly: 
    docker: 
      - 
        image: circleci/php
    steps: 
      - 
        attach_workspace: 
          at: ~/jinya/
      - 
        run: 
          command: "scp -r ~/jinya/dist $DEPLOY_LOGIN@$DEPLOY_SERVER:$DEPLOY_TARGET/cms/nightly ssh $DEPLOY_LOGIN@$DEPLOY_SERVER \"php_cli $DEPLOY_TARGET/bin/console jinya:version:update nightly\"\n"
          name: "Deploy via SCP"
    working_directory: ~/jinya
  deployStable: 
    docker: 
      - 
        image: circleci/php
    steps: 
      - 
        attach_workspace: 
          at: ~/jinya/
      - 
        run: 
          command: "scp -r ~/jinya/dist $DEPLOY_LOGIN@$DEPLOY_SERVER:$DEPLOY_TARGET/cms/stable ssh $DEPLOY_LOGIN@$DEPLOY_SERVER \"php_cli $DEPLOY_TARGET/bin/console jinya:version:update stable\"\n"
          name: "Deploy via SCP"
    working_directory: ~/jinya
version: 2
workflows: 
  edge: 
    jobs: 
      - build
      - 
        deployEdge: 
          requires: 
            - build
  nightly: 
    jobs: 
      - build
      - 
        deployNightly: 
          requires: 
            - build
    triggers: 
      - 
        schedule: 
          cron: "0 0 * * *"
          filters: 
            branches: 
              only: 
                - develop
  stable: 
    jobs: 
      - build
      - 
        deployStable: 
          requires: 
            - build
    triggers: 
      - 
        schedule: 
          cron: "0 0 * * 6"
          filters: 
            branches: 
              only: 
                - master
  version: 2
