---
- name: Create jinya directory
  file:
    path: /var/www/jinya/
    state: directory
    mode: 0755
  become: yes
- name: Sync files to location
  synchronize:
    src: /vagrant/
    dest: /var/www/jinya/
    delete: yes
    recursive: yes
  become: true
- name: Change permissions
  file:
    path: /var/www/jinya/
    mode: u=xrw,g=xrw,o=xrw
    owner: apache
    group: apache
    recurse: yes
  become: yes