---
- name: Add yarn repo
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
  become: true
- name: Install node
  yum:
    name: https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
    state: present
  become: true
- name: Install rsync, inotify and utilities
  yum:
    name:
      - gcc-c++
      - make
      - yarn
  become: true